/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimestampsRouteImport } from './routes/timestamps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimestampsTimestampIdRouteImport } from './routes/timestamps.$timestampId'

const TimestampsRoute = TimestampsRouteImport.update({
  id: '/timestamps',
  path: '/timestamps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampsTimestampIdRoute = TimestampsTimestampIdRouteImport.update({
  id: '/$timestampId',
  path: '/$timestampId',
  getParentRoute: () => TimestampsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/timestamps': typeof TimestampsRouteWithChildren
  '/timestamps/$timestampId': typeof TimestampsTimestampIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/timestamps': typeof TimestampsRouteWithChildren
  '/timestamps/$timestampId': typeof TimestampsTimestampIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/timestamps': typeof TimestampsRouteWithChildren
  '/timestamps/$timestampId': typeof TimestampsTimestampIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-account'
    | '/login'
    | '/timestamps'
    | '/timestamps/$timestampId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-account'
    | '/login'
    | '/timestamps'
    | '/timestamps/$timestampId'
  id:
    | '__root__'
    | '/'
    | '/create-account'
    | '/login'
    | '/timestamps'
    | '/timestamps/$timestampId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateAccountRoute: typeof CreateAccountRoute
  LoginRoute: typeof LoginRoute
  TimestampsRoute: typeof TimestampsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timestamps': {
      id: '/timestamps'
      path: '/timestamps'
      fullPath: '/timestamps'
      preLoaderRoute: typeof TimestampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestamps/$timestampId': {
      id: '/timestamps/$timestampId'
      path: '/$timestampId'
      fullPath: '/timestamps/$timestampId'
      preLoaderRoute: typeof TimestampsTimestampIdRouteImport
      parentRoute: typeof TimestampsRoute
    }
  }
}

interface TimestampsRouteChildren {
  TimestampsTimestampIdRoute: typeof TimestampsTimestampIdRoute
}

const TimestampsRouteChildren: TimestampsRouteChildren = {
  TimestampsTimestampIdRoute: TimestampsTimestampIdRoute,
}

const TimestampsRouteWithChildren = TimestampsRoute._addFileChildren(
  TimestampsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateAccountRoute: CreateAccountRoute,
  LoginRoute: LoginRoute,
  TimestampsRoute: TimestampsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
